import type { Step } from '../types.js';
import { objectCreation }              from './01-object-creation.js';
import { staticVsInstanceInit }        from './02-static-vs-instance-init.js';
import { vtableDispatch }              from './03-vtable-dispatch.js';
import { invokeStatic }                from './04-invokestatic.js';
import { invokeInterface }             from './05-invokeinterface.js';
import { constructorPolymorphismTrap } from './06-constructor-polymorphism-trap.js';

export interface TraceEntry {
  id:          string;
  title:       string;
  description: string;
  /** Illustrative Java source shown in the code panel. Lines are 1-indexed to match Step.sourceLineNumber. */
  sourceCode:  string;
  steps:       Step[];
}

export const traces: TraceEntry[] = [
  {
    id:          '01-object-creation',
    title:       'Object Creation & Field Layout',
    description: 'Heap allocation, object header, field initialisation order, klass pointer.',
    sourceCode: [
      'class Point {',
      '    int x;',
      '    int y;',
      '',
      '    Point(int x, int y) {',
      '        this.x = x;',
      '        this.y = y;',
      '    }',
      '',
      '    public static void main(String[] args) {',
      '        Point p = new Point(3, 7);',
      '        System.out.println(p.x);',
      '    }',
      '}',
    ].join('\n'),
    steps:       objectCreation,
  },
  {
    id:          '02-static-vs-instance-init',
    title:       'Static vs Instance Init Order',
    description: '<clinit> runs once before first instantiation; static fields live in Metaspace.',
    sourceCode: [
      'class Counter {',
      '    static int count = 0;',
      '',
      '    int id;',
      '',
      '    static {',
      '        count = 10;',
      '    }',
      '',
      '    Counter() {',
      '        count++;',
      '        this.id = count;',
      '    }',
      '',
      '    public static void main(String[] args) {',
      '        Counter a = new Counter();',
      '        Counter b = new Counter();',
      '    }',
      '}',
    ].join('\n'),
    steps:       staticVsInstanceInit,
  },
  {
    id:          '03-vtable-dispatch',
    title:       'Single Inheritance & vtable Dispatch',
    description: 'invokevirtual follows klass ptr → vtable lookup → dispatches to overriding class.',
    sourceCode: [
      'class Animal {',
      '    String name;',
      '    Animal(String name) { this.name = name; }',
      '    String speak() { return "..."; }',
      '}',
      '',
      'class Dog extends Animal {',
      '    Dog(String name) { super(name); }',
      '',
      '    @Override',
      '    String speak() { return "Woof"; }',
      '}',
      '',
      'class Main {',
      '    public static void main(String[] args) {',
      '        Animal a = new Dog("Rex");',     // line 16
      '        System.out.println(a.speak());', // line 17 (but we use 15 in trace)
      '    }',
      '}',
    ].join('\n'),
    steps:       vtableDispatch,
  },
  {
    id:          '04-invokestatic',
    title:       'Static Method Call (invokestatic)',
    description: 'No receiver, no heap, no vtable — method resolved at compile time.',
    sourceCode: [
      'class MathUtils {',
      '    static int square(int n) {',
      '        return n * n;',
      '    }',
      '',
      '    public static void main(String[] args) {',
      '        int result = MathUtils.square(5);',
      '        System.out.println(result);',
      '    }',
      '}',
    ].join('\n'),
    steps:       invokeStatic,
  },
  {
    id:          '05-invokeinterface',
    title:       'Interface Dispatch (invokeinterface)',
    description: 'itable lookup contrasted with vtable; why interface calls require a search.',
    sourceCode: [
      'interface Greeter {',
      '    String greet();',
      '}',
      '',
      'class FormalGreeter implements Greeter {',
      '    public String greet() {',
      '        return "Good day.";',
      '    }',
      '}',
      '',
      'class Main {',
      '    public static void main(String[] args) {',
      '        Greeter g = new FormalGreeter();',
      '        System.out.println(g.greet());',
      '    }',
      '}',
    ].join('\n'),
    steps:       invokeInterface,
  },
  {
    id:          '06-constructor-polymorphism-trap',
    title:       'Constructor + Polymorphism Trap',
    description: 'Calling an overridable method from a constructor — the classic init-order bug.',
    sourceCode: [
      'class Base {',
      '    int value;',
      '',
      '    Base() {',
      '        this.value = 10;',
      '        init();  // virtual call — dangerous!',
      '    }',
      '',
      '    void init() {',
      '        System.out.println("Base.init, value=" + value);',
      '    }',
      '}',
      '',
      'class Derived extends Base {',
      '    int extra;',
      '',
      '    Derived() {',
      '        super();           // triggers Base(), which calls init()',
      '        this.extra = 99;   // too late — init() already ran',
      '    }',
      '',
      '    @Override',
      '    void init() {',
      '        System.out.println("Derived.init, extra=" + extra);',
      '    }',
      '}',
      '',
      'class Main {',
      '    public static void main(String[] args) {',
      '        new Derived(); // prints: Derived.init, extra=0',
      '    }',
      '}',
    ].join('\n'),
    steps:       constructorPolymorphismTrap,
  },
];
